export interface checklist {
    estado_bus: string,
    fecha_hora: string,
    aux_salida: string,
    operador: string,
    lic_conduccion: string,
    carne_arl: string,
    carne_empresa: string,
    ruta: string,
    servicio_bus: string,
    baja_presion: string,
    falla_alternador: string,
    num_bus: string,
    palanca_freno: string,
    pedal_freno: string,
    alta_tempMotor: string,
    freno_seg: string,
    falla_motor: string,
    falla_ABS: string,
    bajoNivel_refrig: string,
    puertaTras_Del: string,
    est_volanteBocina: string,
    luces_altBajas: string,
    tipo_servicio: string,
    luces_laterales: string,
    est_Panoramicos: string,
    espejos_interExter: string,
    TFT: string,
    novedad_TFT: string,
    radio: string,
    novedades_radio: string,
    torniquete: string,
    validador: string,
    rutero_frontal: string,
    rutero_lateral: string,
    rutero_trasero: string,
    novedades_EquipoComuni: string,
    matricula: string,
    soat: string,
    tarj_operacion: string,
    tecnomecanica: string,
    botiquin: string,
    cant_extintores: string,
    cant_conos: string,
    novedades_varias: string,
    medida_gas: string,
    tec_asignado: string,
    descrip_mant: string,
    fecha_mant: string,
    numero_OT: string,
    responsable_mnto: string,
    checklist_registro: string,
    est_despacho: string,
    lugar_atencion: string,
    manometro_extintor: string,
    PINSeguridad_extintor: string,
    manija_extintor: string,
    vencimiento_extintor: string,
    boquilla_extintor: string,
    fechaHora_Servicio: string,
    silla_corre: string,
    silla_subeBaja: string,
    silla_torcida: string,
    sillaLinea_volante: string,
    espaldar_silla: string,
    obs_silla: string,
    PMR: string,
    cinturon: string
}


export type checklistKeys =  
'estado_bus'  |
'fecha_hora'  |
'aux_salida'  |
'operador'  |
'lic_conduccion'  |
'carne_arl'  |
'carne_empresa'  |
'ruta'  |
'servicio_bus'  |
'baja_presion'  |
'falla_alternador'  |
'num_bus'  |
'palanca_freno'  |
'pedal_freno'  |
'alta_tempMotor'  |
'freno_seg'  |
'falla_motor'  |
'falla_ABS'  |
'bajoNivel_refrig'  |
'puertaTras_Del'  |
'est_volanteBocina'  |
'luces_altBajas'  |
'tipo_servicio'  |
'luces_laterales'  |
'est_Panoramicos'  |
'espejos_interExter'  |
'TFT'  |
'novedad_TFT'  |
'radio'  |
'novedades_radio'  |
'torniquete'  |
'validador'  |
'rutero_frontal'  |
'rutero_lateral'  |
'rutero_trasero'  |
'novedades_EquipoComuni'  |
'matricula'  |
'soat'  |
'tarj_operacion'  |
'tecnomecanica'  |
'botiquin'  |
'cant_extintores'  |
'cant_conos'  |
'novedades_varias'  |
'medida_gas'  |
'tec_asignado'  |
'descrip_mant'  |
'fecha_mant'  |
'numero_OT'  |
'responsable_mnto'  |
'checklist_registro'  |
'est_despacho'  |
'lugar_atencion'  |
'manometro_extintor'  |
'PINSeguridad_extintor'  |
'manija_extintor'  |
'vencimiento_extintor' | 
'boquilla_extintor'  |
'fechaHora_Servicio'  |
'silla_corre'  |
'silla_subeBaja'  |
'silla_torcida'  |
'sillaLinea_volante'  |
'espaldar_silla'  |
'obs_silla'  |
'PMR'  |
'cinturon'