import { Schema, model } from 'mongoose'
import { checklist } from '../../types'


const checklistSchame = new Schema<checklist> ({
    estado_bus: String,
    fecha_hora: String,
    aux_salida: String,
    operador: String,
    lic_conduccion: String,
    carne_arl: String,
    carne_empresa: String,
    ruta: String,
    servicio_bus: String,
    baja_presion: String,
    falla_alternador: String,
    num_bus: String,
    palanca_freno: String,
    pedal_freno: String,
    alta_tempMotor: String,
    freno_seg: String,
    falla_motor: String,
    falla_ABS: String,
    bajoNivel_refrig: String,
    puertaTras_Del: String,
    est_volanteBocina: String,
    luces_altBajas: String,
    tipo_servicio: String,
    luces_laterales: String,
    est_Panoramicos: String,
    espejos_interExter: String,
    TFT: String,
    novedad_TFT: String,
    radio: String,
    novedades_radio: String,
    torniquete: String,
    validador: String,
    rutero_frontal: String,
    rutero_lateral: String,
    rutero_trasero: String,
    novedades_EquipoComuni: String,
    matricula: String,
    soat: String,
    tarj_operacion: String,
    tecnomecanica: String,
    botiquin: String,
    cant_extintores: String,
    cant_conos: String,
    novedades_varias: String,
    medida_gas: String,
    tec_asignado: String,
    descrip_mant: String,
    fecha_mant: String,
    numero_OT: String,
    responsable_mnto: String,
    checklist_registro: String,
    est_despacho: String,
    lugar_atencion: String,
    manometro_extintor: String,
    PINSeguridad_extintor: String,
    manija_extintor: String,
    vencimiento_extintor: String,
    boquilla_extintor: String,
    fechaHora_Servicio: String,
    silla_corre: String,
    silla_subeBaja: String,
    silla_torcida: String,
    sillaLinea_volante: String,
    espaldar_silla: String,
    obs_silla: String,
    PMR: String,
    cinturon: String
})

export const checklistModel = model('CheckList', checklistSchame)


